runtime: php
env: flex

runtime_config: document_root: public

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

env_variables:
    # Put production environment variables here.
    APP_DEBUG: true
    APP_ENV: production
    APP_KEY: base64:vllrxfneF+o0fs7IxLj/0Iw0YSuF/N6WpYj8uPt4evI=
    APP_NAME: "Bliss Wine Imports"

    LOG_LEVEL: debug

    DB_DATABASE: bliss-db-instance-001
    DB_USERNAME: root
    DB_PASSWORD:
    DB_SOCKET: '/cloudsql/southern-sol-364603:us-central1:bliss-db-instance-001'

beta_settings:
cloud_sql_instances: 'southern-sol-364603:us-central1:bliss-db-instance-001'