name: Deploy to PROD
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - name: 📂 Git Push
        run: git push prod main
      # - name: Copy .env
      #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      # - name: Install Dependencies
      #   run: composer update --ignore-platform-reqs
      # - name: Generate key
      #   run: php artisan key:generate
      # - name: Directory Permissions
      #   run: chmod -R 777 storage bootstrap/cache
